name: WakaTime Graph Generator

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:

jobs:
  build-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests matplotlib

      - name: Generate Graph
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          python scripts/generate_graph.py

      - name: Commit graph
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add waka_graph.png
          git commit -m "update: waka graph" || echo "No changes to commit"
          git push
